version: "2.12.0"

services:
  app:
    image: channels
    depends_on:
      - cache
    volumes:
      - static:/usr/src/app/static
    ports:
      - 8888:8888
    restart: always


  db:
    image: postgres:15.1-alpine3.16
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 220914Rulu
      POSTGRES_DB: channels
    restart: always


  cache:
    image: redis:7.0-alpine3.16
    depends_on:
      - db
    ports:
      - 6379:6379
    restart: always


volumes:
  dbdata:
  static: